version: '3'
services:
  app1:
    build: ./tomcat
    container_name: app1
    ports:
      - 8081:8080
    volumes:
      - ./tomcat/webapps/myapp:/usr/local/tomcat/webapps/myapp
  app2:
    build: ./tomcat
    container_name: app2
    ports:
      - 8082:8080
    volumes:
      - ./tomcat/webapps/myapp:/usr/local/tomcat/webapps/myapp
  loadbalancer:
    build: ./apache
    ports:
      - 80:80